module.exports = grammar({
  name: 'kalcite',
  extras: $ => [/\s/, $.comment],
  word: $ => $.identifier,
  conflicts: $ => [[$.field_declaration, $.local_declaration]],
  rules: {
    source_file: $ => repeat($._declaration),
    comment: _ => token(choice(seq('//', /.*/), seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/'))),
    _declaration: $ => choice($.module_declaration, $.use_declaration, $.class_declaration, $.struct_declaration, $.function_declaration, $.field_declaration, $.signal_declaration),
    module_declaration: $ => seq('module', $.identifier, repeat(seq('.', $.identifier)), ';'),
    use_declaration: $ => seq('use', $.identifier, repeat(seq('.', $.identifier)), ';'),
    attributes: $ => repeat1(seq('@', $.identifier, optional(seq('(', optional(commaSep($._expression)), ')')))),
    class_declaration: $ => seq(optional($.attributes), 'class', field('name', $.identifier), optional(seq('extends', $.identifier)), $.block),
    struct_declaration: $ => seq(optional($.attributes), 'struct', field('name', $.identifier), $.block),
    function_declaration: $ => seq(optional($.attributes), 'fn', field('name', $.identifier), '(', optional(commaSep($.parameter)), ')', optional(seq('->', $._type)), $.block),
    parameter: $ => seq($.identifier, ':', $._type),
    field_declaration: $ => seq(optional($.attributes), choice('var', 'const'), $.identifier, ':', $._type, optional(seq('=', $._expression)), ';'),
    signal_declaration: $ => seq(optional($.attributes), 'signal', field('name', $.identifier), '(', optional(commaSep($.parameter)), ')', ';'),
    block: $ => seq('{', repeat(choice($._declaration, $.statement)), '}'),
    statement: $ => choice(
      $.native_statement,
      $.local_declaration,
      $.assignment_statement,
      $.if_statement,
      $.while_statement,
      $.break_statement,
      $.continue_statement,
      seq($._expression, ';'),
      $.block,
      seq('defer', $._expression, ';'),
      seq('return', optional($._expression), ';')
    ),
    native_statement: $ => seq('unsafe', choice('rust', 'asm'), optional(seq('[', $.identifier, ']')), '{', optional($.native_body), '}'),
    native_body: _ => token(/[^}]+/),
    local_declaration: $ => choice(
      seq('var', $.identifier, optional(seq(':', $._type)), optional(seq('=', $._expression)), ';'),
      seq('const', choice(seq($._type, $.identifier), seq($.identifier, optional(seq(':', $._type)))), optional(seq('=', $._expression)), ';'),
      seq($._type, $.identifier, optional(seq('=', $._expression)), ';')
    ),
    if_statement: $ => seq('if', field('condition', $._expression), field('consequence', $.block), optional(seq('else', choice($.if_statement, field('alternative', $.block))))),
    while_statement: $ => seq('while', field('condition', $._expression), field('body', $.block)),
    break_statement: _ => seq('break', ';'),
    continue_statement: _ => seq('continue', ';'),
    assignment_statement: $ => seq(field('left', $._expression), choice('=', '+=', '-=', '*=', '/='), field('right', $._expression), ';'),
    _expression: $ => choice(
      $.identifier,
      $.number,
      $.string,
      $.array,
      $.parenthesized_expression,
      $.member_expression,
      $.call,
      $.unary_expression,
      $.binary_expression
    ),
    parenthesized_expression: $ => seq('(', $._expression, ')'),
    member_expression: $ => prec.left(10, seq(field('object', $._expression), '.', field('property', $.identifier))),
    call: $ => prec.left(11, seq(field('function', $._expression), '(', optional(commaSep($._expression)), ')')),
    unary_expression: $ => prec(9, seq(choice('!', '-'), $._expression)),
    binary_expression: $ => choice(
      prec.left(8, seq($._expression, choice('*', '/', '%'), $._expression)),
      prec.left(7, seq($._expression, choice('+', '-'), $._expression)),
      prec.left(6, seq($._expression, choice('<', '<=', '>', '>='), $._expression)),
      prec.left(5, seq($._expression, choice('==', '!='), $._expression)),
      prec.left(4, seq($._expression, '&', $._expression)),
      prec.left(3, seq($._expression, choice('|', '^'), $._expression)),
      prec.left(2, seq($._expression, '&&', $._expression)),
      prec.left(1, seq($._expression, '||', $._expression))
    ),
    array: $ => seq('[', optional(commaSep($._expression)), ']'),
    _type: $ => choice($.identifier, seq('[', $._type, ';', $.number, ']'), seq($.identifier, '[', $._type, optional(seq(';', $.number)), ']')),
    identifier: _ => /[A-Za-z_][A-Za-z0-9_]*/,
    number: _ => /0x[0-9A-Fa-f_]+|0b[01_]+|[0-9][0-9_]*/,
    string: _ => /"([^"\\]|\\.)*"/,
  }
});

function commaSep(rule) { return seq(rule, repeat(seq(',', rule)), optional(',')); }
